--  Auto Generated by FMCS
--  Add custom data to prototypes/data_custom.lua

data:extend({
    {
        type = "item",
        name = "fmcs-test-item",
        icon = "__fmcs-template__/graphics/icons/fmcs-item.png",
        icon_size = 64,
        subgroup = "raw-resource",
        order = "z[u]",
        stack_size = 100
    }
});
