--  Auto Generated by FMCS
--  Add custom data to prototypes/data_custom.lua

data:extend({
    {
        type = "recipe",
        name = "fmcs-test-item",
        enabled = true,
        energy_required = 1,
        ingredients = {
            { type = "item", name = "wood", amount = 1 },
        },
        results = { { type = "item", name = "fmcs-test-item", amount = 1 } }
    }
});
