--  Auto Generated by FMCS
--  Add custom control code to controls/control_custom.lua

-- Contains runtime scripting (event-driven logic),
-- like on_tick, on_built_entity, etc. It only runs in-game,
-- not during mod loading.

require("controls.autogen.fmcs-auto-commands")

require("controls.control_custom")