--  Auto Generated by FMCS
--  Add custom data to prototypes/data_custom.lua

require("prototypes.autogen.fmcs-auto-items")
require("prototypes.autogen.fmcs-auto-recipes")

require("prototypes.data_custom")