// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fQVQPOOOeQPO'#C_OjQQO'#CiOOQO'#Ci'#CiOOQO'#Cd'#CdQVQPOOOoQPO'#CcOtQQO'#CbOOQO'#Ce'#CeQ`QPOOOyQQO,58yOOQO,59T,59TOOQO-E6b-E6bO!OQPO,58}O!TQPO,58|OOQO-E6c-E6cOOQO1G.e1G.eOOQO1G.i1G.iO!fQPO1G.h",
  stateData: "!z~O[OS~OQQOSPO`ROaUO~O^YO~O_ZO~OS]O~O_^O~OT`O~ObaO~OQQOSPO`ROYUaaUa~OQQOSPO`ROYUiaUi~O[T~",
  goto: "!W^PPP_PPejoyPPP!QXQOT^bVWOTXVVOTXQTOS[TbRb^SXOTR_XXSOT^b",
  nodeNames: "⚠ Unit Comment Property Name Value Section SectionHeader",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "(r~RiOX!pXY#yYZ$mZp!ppq#yqs!pst$tt!Q!p!Q![&R![!]!p!]!^$t!^!_!p!_!`'O!`!c!p!c!}&R!}#O'i#O#P#X#P#Q(S#Q#T!p#T#o&R#o;'S!p;'S;=`#s<%l~!p~O!p~~(mQ!uUTQOY!pZ#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pQ#^VTQOY!pYZ!pZ#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pQ#vP;=`<%l!p~$QX[~TQOX!pXY#yZp!ppq#yq#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pR$tO`P_QR${UQPTQOY$tZ#O$t#O#P%_#P;'S$t;'S;=`%{<%lO$tR%fVQPTQOY$tYZ!pZ#O$t#O#P%_#P;'S$t;'S;=`%{<%lO$tR&OP;=`<%l$tR&Y[SPTQOY!pZ!Q!p!Q![&R![!c!p!c!}&R!}#O!p#O#P#X#P#T!p#T#o&R#o;'S!p;'S;=`#s<%lO!pR'VU^PTQOY!pZ#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pR'pUaPTQOY!pZ#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pR(ZUbPTQOY!pZ#O!p#O#P#X#P;'S!p;'S;=`#s<%lO!pQ(rO_Q",
  tokenizers: [0, 1],
  topRules: {"Unit":[0,1]},
  tokenPrec: 85
})
